function info = getReqFieldNames()
%

% Copyright 2020 The MathWorks, Inc.

info = struct('Filename',string([]),...
    'FileModDate',string([]),...
    'FileSize',[],...
    'Format',string([]),...
    'FormatVersion','',...
    'SensorType',string([]),...
    'Description',string([]),...
    'AcquisitionTime',string([]),...,
    'RasterFormat',string([]),...,
    'Height',[],...
    'Width',[],...
    'Bands',[],...
    'DataType',string([]),...
    'Interleave',string([]),...
    'HeaderOffset',[],...
    'ByteOrder',string([]),...
    'BandNames',string([]),...
    'Wavelength',[],...
    'FWHM',[],...
    'Gain',[],...
    'Offset',[],...
    'ReflectanceGain',[],...
    'ReflectanceOffset',[],...
    'BadBands',logical([]),...
    'CloudCover',[],...
    'SunAzimuth',[],...
    'SunElevation',[],...
    'SolarIrradiance',[],...
    'EarthSunDistance',[],...
    'WavelengthUnits',string([]));
end